name: supa_app
version: 0.1.0
publish_to: none
description: A new Flutter project.
environment:
  sdk: ^3.1.5

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.1
  get: 4.6.6
  json_annotation: ^4.8.1
  localization:
    path: ../localization
  logging: ^1.2.0
  supabase_flutter: ^2.0.1
  utils:
    path: ../utils 

dev_dependencies:
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  pro_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - .env
